const SET_DANH_MUC = "SET_DANH_MUC";

const SET_DANH_SACH_YEU_THICH = "SET_DANH_SACH_YEU_THICH";
const THEM_DANH_SACH_YEU_THICH = "THEM_DANH_SACH_YEU_THICH";
const XOA_DANH_SACH_YEU_THICH = "XOA_DANH_SACH_YEU_THICH";

const SET_CART_ITEM = "SET_CART_ITEM";
const THEM_CART_ITEM = "THEM_CART_ITEM";
const XOA_CART_ITEM = "XOA_CART_ITEM";
const THEM_SO_LUONG_CART_ITEM = "THEM_SO_LUONG_CART_ITEM";

const SET_IS_OPEN_DANH_MUC = "SET_IS_OPEN_DANH_MUC";
export {
  SET_DANH_MUC,
  SET_DANH_SACH_YEU_THICH,
  XOA_DANH_SACH_YEU_THICH,
  THEM_DANH_SACH_YEU_THICH,
  SET_CART_ITEM,
  THEM_CART_ITEM,
  XOA_CART_ITEM,
  THEM_SO_LUONG_CART_ITEM,
  SET_IS_OPEN_DANH_MUC,
};
